Rebalance IG Boni
MasterSon-git/vic3-kmpmp pull request #165
Opened 2024-03-04 13:40 UTC by Tziplays

Mexico:
add normal Army IG buffs on top of authority

Bolivia:
add normal Army IG buffs on top of authority

Brasil:
add Tech buff to inteligentsia IG
add Tech buff to Industrialists IG

France
change buff to 15% off 5% Def (30% Off 10% Def at powerful)

Persia:
add 5% EA to the one with 50% conversion

Egypt/Ottomans:
add 5% EA to the one with 50% conversion

Sweden:
industrialists IG
add 2.5% manufacturing income to the idea with mining income

Japan:
Church ig
change -50% -> -15% radicals from Sol decrease
add +1% pop growth

industrialists:
add 5% constr eff to zaibatsu

Prussia:
industrialist IG:
add 2.5% manufacturing TP to second passive
rename passive to Made in Germany

2024-03-04 17:54 UTC, MasterSon-git requested changes

2024-03-04 17:54 UTC, MasterSon-git commented on src/common/interest_group_traits/kmpmp_00_devout_traits.txt
> +		state_radicals_from_sol_change_mult = -0.15 #0.5
should be positive

2024-03-04 17:54 UTC, MasterSon-git commented on src/common/interest_group_traits/kmpmp_00_devout_traits.txt
> +		state_accepted_birth_rate_mult = 0.01
not only accepted pops

2024-03-04 17:54 UTC, MasterSon-git commented on src/common/interest_groups/kmpmp_00_industrialists.txt
> +﻿	ig_industrialists = {
indents

2024-03-04 17:54 UTC, MasterSon-git commented on src/localization/english/kmpmp_l_english.yml
> + kmpmp_ig_trait_made_in_germany:0 "Deutsche Qualität?"
why not "Made in Germany"?

2024-03-05 11:48 UTC, Tziplays commented on src/common/interest_group_traits/kmpmp_00_devout_traits.txt
> +		state_radicals_from_sol_change_mult = -0.15 #0.5
ist gemacht

2024-03-05 19:13 UTC, MasterSon-git approved these changes

2024-03-05 19:13 UTC, merged