399 block rebalance
MasterSon-git/vic3-kmpmp pull request #417
Opened 2024-11-08 19:37 UTC by Waysten

2024-11-08 21:03 UTC, MasterSon-git requested changes
where is this?
`nerf own leverage generation from pops by another 20%`

2024-11-08 21:03 UTC, MasterSon-git commented on src/common/power_bloc_principles/kmpmp_00_power_bloc_principles.txt
> +		state_market_access_price_impact = 0.05
comment as `#kmpmp` modifier

2024-11-08 21:03 UTC, MasterSon-git commented on src/common/power_bloc_principles/kmpmp_00_power_bloc_principles.txt
> +		country_authority_add = 75
comment for vanilla value

2024-11-08 21:03 UTC, MasterSon-git commented on src/common/power_bloc_principles/kmpmp_00_power_bloc_principles.txt
> +		country_military_goods_cost_mult = -0.05
comment as `#kmpmp` modifier

2024-11-08 21:03 UTC, MasterSon-git commented on src/common/production_methods/kmpmp_08_monuments.txt
> +			state_conversion_mult = 1
comment vanilla value

2024-11-08 21:04 UTC, Waysten commented on src/common/power_bloc_identities/kmpmp_00_power_bloc_identities.txt
> +
ah mist hat er nicht gespeichert

2024-11-08 21:05 UTC, Waysten commented on src/common/script_values/zz_kmpmp_01_power_bloc_values.txt
> +            value = 300 #200
o.O siehe Discord oder gab es eben eine neue Absprache?

2024-11-09 13:47 UTC, MasterSon-git approved these changes

2024-11-09 13:50 UTC, merged